server:
  port: 80
cors:
  originPatterns: http://0.0.0.0:8080,https://erudio.com.br,http://localhost:3000
file:
  upload-dir: /Dan/DEV/BACK/rest-with-spring-boot-and-java-erudio/UploadDir
security:
  jwt:
    token:
      secret-key: 53ccr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: Danilo2023**
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathstoMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true